export const API_ROUTES = {
   LOGIN: "users/login",
   SIGNUP: "users/signup",
   USER_LIST: "users/getAllUsersByType?type=3",
   USER_DELETE: "users/deleteUsers",
   USER_EDIT: "users/editUser/",
   EVENT_LIST: "event/getAllEvents?",
   PROFILE: "users/profile",
   EDIT_PROFILE: "users/updateProfile",
   ADD_EVENT: "event/addEvent",
   UPDATE_EVENT: "event/updateEvent/",
   DELETE_EVENT: "event/deleteEvent/",
   ACTIVITIESADMIN: "activities/getAllActivities",
   DASHBORADAPI: "dashboard/overview",
   ANALYTICSDATA: "analysis/type3?",
   ACTIVITIESUSER: "activities/getUserActivities",
   RESETPASSWORD: 'users/resetPassword',
   RESETCODE: "users/verifyResetCode",
   CREATE_ROOM:"accent/create-room",
   ROOMLINK_GENRATE:"accent/create_room",
}
